### ISSUE TITLE
Reported bugs

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ku-migration#18]
- [ ] KU drives keep dropping off 
- [ ] Can't access T drive
- [ ] Can't access Z drive (directory)
- [ ] Groups in MS 365 exchange don't seem to work*?  (SLS needed to add individuals)

> Another issue (not to do with changing computer) is that in MS365 it seems that shared mailboxes do not appear in our outlook inboxes if the access is granted to a group in MS365. For example, I have had to add myself as an individual person to the Travel, Bulletin Board, GB23 shared mailboxes as it does not recognize (anymore, used to do it) groups such as “Staff”, “Travel Group” etc. We first experienced the problem when I added Mette to such groups and I ended up having to add her as an individual instead. I remember Matt and I discussed it, but at the time we did not find out what the issue was. As mentioned, it seems to be something that has changed since we started using MS365.

**Comment by MattBlissett** [comment]
Directory: Change /etc/httpd/conf.d/directory-vh.conf, which needs the KU IP added. I don't know if this file is generate from somewhere else.

**Comment by MattBlissett** [comment]
T drive: I suggest we move it to box.com. Otherwise, I'll need to look at the firewall on Aino.

**Comment by cgendreau** [comment]
Yes I will update the Directory Ansible script I just need the IP range I need to add.

**Comment by MattBlissett** [comment]
The single IP `130.225.98.120`.
