### ISSUE TITLE
Open ports in the firewall

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ku-migration#25]
We need to open [a ticket in KU](https://propel.ku.dk:9000/org/ku) to enable the following (ports etc)

- [ ] Connect to all services when on VPN without port forwarding
- [ ] Jenkins needs to access GitHub, Contentful and Mendeley 
- [ ] TDWG servers (web etc) use GitHub I think 
- [ ] http://drupaledit.gbif.org/ needs to be open (VPN)
- [ ] Bla6 needs to be open to crawl the world
- [ ] Hadoop gateway machines need t be able to pull configs from Git

**Comment by mdoering** [comment]
does that include all servers that need to ssh to git(hub)?
 - bla6 uses git for cli configs
 - hadoop gateways checkout git projects for index builds

**Comment by MattBlissett** [comment]
I will ask for:

* vpn-gbif.science.ku.dk all ports →
* servers, on ports 22, 53, 80, 123, 443, 11371 → anyone

We then need to catch anything that doesn't fall into that.  Github (either SSH, HTTP or HTTPS), Contentful, Mendeley, TDWG, Hadoop are dealt with by the second rule. Drupaledit by the first. Bla6 is already done.

CentOS installs/updates are HTTP.

I've emailed Sune.

**Comment by MattBlissett** [comment]
I've submitted it through the ticket thing, it's case PT35734
